### ISSUE TITLE
SDL_ttf font device

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/xsystem35-sdl2#12]
I've been working an a PS Vita port of xsystem35 recently. The first thing I noticed when I got it running was that text rendering using the freetype2 font device is extremely slow (it must be rendering on the CPU or something). So I fixed up the SDL_ttf font device (see [here](https://github.com/nunuhara/xsystem35-vita/commit/ebeb9d334ea23ba1d6f1ca38632e5233092b1330)) hoping it would improve performance, and it did (at least 5x faster, if I had to guess). I think the main difference is that SDL_ttf keeps a cache of rendered glyphs.

Would you be interested in accepting a patch to add the SDL_ttf font device here as well?

**Comment by kichikuou** [comment]
Nice! I'd love to merge the patch here.

And your Vita port is really cool :)

**Comment by nunuhara** [comment]
Thanks :)

How should I set the defaults?
* If SDL is enabled, and no font device is specified, it currently defaults to using freetype. Should I leave it as is or change it to SDL_ttf (if it's available)?
* if "ttf" is specified as the font device (on the command line or in .xsys35rc), and both freetype and SDL_ttf are available, which should be used?

**Comment by kichikuou** [comment]
- If SDL_ttf is available, using it by default sounds good (because it's faster).
- "ttf" was originally used to represent (now deprecated) FreeType1 font device. Currently it's an alias of "ft2", but but that may be confusing when SDL_ttf is added. Also, "ttf" is a bit storange as a font device name (because it's a font format name).

How about this?
- "ft2" and "sdl" are the supported font device names
- Xsystem35 doesn't recognize "ttf" and falls back to the default

i.e.:
```C
#ifdef ENABLE_SDLTTF
#define DEFAULT_FONT_DEVICE FONT_SDLTTF
#elif defined(ENABLE_SDL)
#define DEFAULT_FONT_DEVICE FONT_FT2
#else
#define DEFAULT_FONT_DEVICE FONT_X11
#endif

static fontdev_t fontdev = DEFAULT_FONT_DEVICE;

...

static int check_fontdev(char *devname) {
#ifdef ENABLE_SDLTTF
	if (0 == strcmp(devname, "sdl")) {
		return FONT_SDLTTF;
	}
#endif
#ifdef ENABLE_FT2
	if (0 == strcmp(devname, "ft2")) {
		return FONT_FT2;
	}
#endif
#ifdef ENABLE_X11FONT
	if (0 == strcmp(devname, "x11")) {
		return FONT_X11;
	}
#endif
	return DEFAULT_FONT_DEVICE;
}
```
