### ISSUE TITLE
Importing savedata from pc to mobile

### ISSUE THREAD

**Issue by notkiriya** [kichikuou/xsystem35-sdl2#33]
I want to import my Kichikuou Rance savedata from my PC to my Phone. I uploaded the files from the pc and then downloaded it to my phone but when I played it, my savedata from the PC wasn't in my phone.  I also discovered that there is an import savedata option but it asks me to get a savedata folder from my Kichikuou Rance in the PC but the save folder does not even exist. How do I import my savedata from the PC to my Phone?

**Comment by kichikuou** [comment]
Are you using [xystem35-sdl2's Windows port](https://github.com/kichikuou/xsystem35-sdl2/releases) to play Kichikuou Rance on your PC? If you're using (original) System39.exe, then you cannot import savedata because the data format is incompatible.

If you're using xsystem35-sdl2 it's possible, although a bit complicated for historical reasons.

1. Create a folder named `save`.
2. Copy `asleep.asd`, `bsleep.asd`, ... from the Kichikuou folder to the `save` folder.
3. Rename `asleep.asd` to `KICHIKUsa.asd`, `bsleep.asd` to `KICHIKUsb.asd`, and so on.
4. Right-click the `save` folder and create a zip from it.
5. Copy the zip file to your phone, and use the "import savedata" menu.
