### ISSUE TITLE
Platform change causes bug

### ISSUE THREAD

**Issue by ultrapre** [kichikuou/xsystem35-sdl2#34]
For かえるにょ・ぱにょ～ん, Win32 exe of [newest](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/3015080558) make noise at the begining (~beep……~beep……), when exe of Version 2.5.1 appears normally.
![image](https://user-images.githubusercontent.com/32613953/190859286-15ab0728-0ee3-44d5-8395-9ce0d6790702.png)

I recompiled v2.5.1, but problem caused again. I compared release version and the version I built, found dll files are different. I supposted it is caused by enviroment difference, like runner version and msys2.

**Comment by kichikuou** [comment]
Is it a buzzing like the audio attached here?
https://github.com/libsdl-org/SDL/issues/6196

**Comment by ultrapre** [comment]
> Is it a buzzing like the audio attached here? [libsdl-org/SDL#6196](https://github.com/libsdl-org/SDL/issues/6196)

Yes

**Comment by kichikuou** [comment]
I guess we'll have to wait for that to be fixed in SDL2.

There's no "supported way" to use an old version of a package in MSYS2 so I won't try to fix it in the automated build. If I need to release the next version of xsystem35 before the SDL2 fix, I'll use the previous version of SDL2 manually.

https://stackoverflow.com/questions/33969803/how-to-obtain-older-versions-of-packages-using-msys2

**Comment by kichikuou** [comment]
Reportedly the SDL2 bug was fixed in 2.26.1, and [this CI run](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/3797955569) is built with SDL2 2.26.1.

@ultrapre  Can you recheck the bug with the above build?

**Comment by kichikuou** [comment]
Closing. Please add a comment if you still have the issue in xsystem35-sdl2 2.6.0.
