### ISSUE TITLE
Rance 4.x (eng) series do not work on Android!

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#49]
Rance 4.1 and Rance 4.2 (english version) cannot be installed because xsystem3.5 requires .ald (not .dat) files. Simply renaming the extension is not enough: after loading them, it does not give an error but immediately exits to the title selection menu.

**Comment by kichikuou** [comment]
These games are not System 3.x but System 3. Try https://github.com/kichikuou/system3-sdl2 instead.

**Comment by KaroNiko** [comment]
Hmm... yet both (ランス４.１ and ランス４．2) are mentioned as supported in the xsystem35 compatibility list. 🤔
However, it's still okay.

**Comment by kichikuou** [comment]
Well, to be more precise, Rance 4.1 and 4.2 have both System 3 and System 3.x versions, because they were [upgraded to System 3.x](https://hannylaboratory.blogspot.com/2023/02/blog-post_9.html) last year by TADA, the original author of the games.

As far as I know, the System 3.x version is only in Japanese and there is no English translation.
