### ISSUE TITLE
Request: directly copy a game folder without installing from zip on Android.

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#52]
Hi. I would like to know if it will be possible in the future to manually copy a game folder to a specific storage location without installing from zip file.
I believe that for now, installed files are not accessible, and therefore I don't understand how to back up saves or modify certain internal files when necessary (e.g., update a translation patch, add a game fix etc).

Also by uninstalling the application to replace it with a newer version, all installed games with related saves will be lost, or am I wrong?
Is there perhaps an alternative way to manually access the installed games that I am missing?

Thank you for your attention. Greetings.

Edit: For the sake of truth, all my posts go back several weeks, but they remained invisible because my profile was flagged for some reason; fortunately, everything is okay now.

**Comment by kichikuou** [comment]
> Hi. I would like to know if it will be possible in the future to manually copy a game folder to a specific storage location without installing from zip file.

Probably not.

Access to device storage by Android apps has become more and more restricted over the years; installing from a ZIP is the only way that seems to continue to work in the future. (xsystem4-android supports direct copying of game folders, but that turned out not to work on some devices, so I had to support installation from ZIP as well.)

> I believe that for now, installed files are not accessible, and therefore I don't understand how to back up saves or modify certain internal files when necessary (e.g., update a translation patch, add a game fix etc).

For save files, you can export / import them from the menu in the upper right corner of the game selection screen.

The only way to replace game files is to create another zip and install it. Save files are managed separately from the game installation, so they will not be lost.

> Also by uninstalling the application to replace it with a newer version, all installed games with related saves will be lost, or am I wrong?

You can install a new version without uninstalling the application. That way your games and saves will be preserved.

> Edit: For the sake of truth, all my posts go back several weeks, but they remained invisible because my profile was flagged for some reason; fortunately, everything is okay now.

Yeah, I was surprised that a number of issues suddenly appeared today that I had not received notifications about 😮
