### ISSUE TITLE
Stuck in KR battle menu

### ISSUE THREAD

**Issue by SupremeJUMBO** [kichikuou/xsystem35-sdl2#56]
### Environment
xsystem35 version: 2.10
OS: Windows 10

### Steps to reproduce the behavior
1. Start any battle in Kichikuou Rance
2. Right-click to open the battle selection menu
3. Right-click again to close the menu

### Expected behavior
When playing the game in System3.9, exiting the battle menu will resume normal mouse tracking and you can click enemies to attack them.

### Actual behavior
When playing in xsystem35, exiting the battle menu will appear to resume normal play, but when you try to click anything, it will just reopen the battle menu. The only way to escape this loop is to right-click twice in a row, which seems to fix the issue until the next time you right-click.

### Additional context
I attempted to fix this with code, by adding ZW 1/2 commands or by changing the value of RND to 32 upon exiting the menu, but nothing worked. For some reason, the game doesn't properly resume mouse tracking when you exit the menu. Also, the box highlights for ally/enemy units will not occur on mouse hover until you've right-clicked a second time. It seems that the code is somehow frozen in place when you close the battle menu with a single click.

**Comment by kichikuou** [comment]
I think the problem is that system3.9 exits the menu immediately when the right button is pressed, whereas xsystem35 waits for the right button to be released before exiting the menu.

Below is the code around the right-click menu. (From unpatched Japanese KR)

```
*L_00563:
        ...                 ; set up the right-click menu
        ]                   ; open the menu
        !VAR1 : 99!
*L_005f2:
        IM VAR202, VAR203:  ; get the mouse button status to RND
        {RND = 0:           ; if no button is pressed
            @L_005f2:       ;    loop
        }
        {RND \ 32:          ; if the right button is not pressed
            @L_00563:       ;    loop back to the right-click menu
        }
*L_00616:
        IM VAR202, VAR203:  ; get the mouse button status to RND
        {RND:               ; if any button is pressed
            @L_00616:       ;    loop
        }
        @L_00348:           ; cancel the menu and resume normal play
```

In system3.9, when the first `IM` command is executed, the right button is still pressed, so RND becomes 32. As a result, it waits for the right button to be released (the loop starting from `*L_00616`) and jumps to `L_00348`.

In xsystem35, the `]` command exits after the right button is released, so it loops on `L_005f2` until some mouse button is pressed. If it is the right button, it returns to `L_00348`, otherwise it shows the right-click menu again.

**Comment by kichikuou** [comment]
In the next version, pressing the right button will immediately exit the menu, just like system3.9.

You can download a build with the fix [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/9559193933). Could you try it and see if it works as expected?

**Comment by SupremeJUMBO** [comment]
Excellent! The bug is fixed. Thanks for the quick work!

**Comment by SupremeJUMBO** [comment]
Close
