### ISSUE TITLE
English Patched Daiakuji Issues on Android Xsystem35-sdl2

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#57]
I am referring to the version of this game with the recent english machine translation (WIP) applied. After loading a save file from the start menu, some character or location names are corrupted and illegible, while others do not have this defect; this seems to happen completely randomly.

Furthermore, the translated text in some places greatly exceeds the space dedicated to it, both in length and height (even off screen) sometimes invading the images considerably. Is it possible to remedy these defects? 
Thanks

![1725909645520](https://github.com/user-attachments/assets/9191ff94-f3e6-4172-8d04-1a65212c27b7)

**Comment by kichikuou** [comment]
I was unable to reproduce the issue with garbled text after saving and loading. Could it be that you loaded data saved before applying the patch, or perhaps updated the patch after the save?

Regarding the string length, xsystem35 is simply displaying the provided string at the given position and size. It's unclear what the game engine itself can do to address this.

From my understanding, the English patch is still in its early stages. I recommend reporting issues to the patch's GitHub project first, unless you're confident that the issue lies with the game engine itself.

**Comment by KaroNiko** [comment]
So I deleted all the save files, closed the application, reopened the application, played and saved again. Now everything seems ok. Who knows what it depended on. I had initially installed the original game in japanese, to test its functioning, in particular the mp3 audio. I actually saved once, but then I completely uninstalled the game and reinstalled the english translated/prepatched version. Then that graphical glitch happened. So my bad. Evidently my inattention.

**Comment by kichikuou** [comment]
The save area in xsystem35 is not partitioned, which can cause problems if two games use the same save file name. Also, uninstalling a game does not delete its save files. I think this explains what happened.

Closing. For the text length issue, please report to the translation project.

**Comment by fcolecumberri** [comment]
@kichikuou Sorry for this, This is my fault, I think my messy MTL might have caused some overflow somewhere. I hope the new release her: https://github.com/fcolecumberri/Doddler_Bizarre_Adventure_in_the_Matriarchy/releases/tag/0.6 wont cause more troubles.

**Comment by kichikuou** [comment]
I would like to clarify that with long strings, the text might overflow the bounds of the text area (as shown in the screenshot from the initial report), but it should not cause a buffer overflow crash or anything like that.

If you encounter such problems, please report them as bugs in xsystem35.
